onejar: app/app

resources: 
- LICENSE
- resources/|**

dependencies:
- ../MultiPortJetty
- ../LiteSoftServerUtils

classpath:
- ../LiteSoftServerUtils/libs|**.jar

compileclasspath:
- ../LinuxVersionedDirUpdater/updater|**.jar
